#!/bin/bash
echo "Running tests 1, 2 and 3"

opp_runall -b1 -j9 opp_run -u Cmdenv -f omnetpp.ini -c test7 -m -n .:../src:../../../../../omnetpp-5.1/samples/inet/examples:../../../../../omnetpp-5.1/samples/inet/src:../../../../../omnetpp-5.1/samples/inet/tutorials:../../../../../omnetpp-5.1/samples/simulte/simulations:../../../../../omnetpp-5.1/samples/simulte/src --image-path=../images:../../../../../omnetpp-5.1/samples/simulte/images -l ../../../../../omnetpp-5.1/samples/inet/src/INET -l ../../../../../omnetpp-5.1/samples/simulte/src/lte

opp_runall -b1 -j9 opp_run -u Cmdenv -f omnetpp.ini -c test8 -m -n .:../src:../../../../../omnetpp-5.1/samples/inet/examples:../../../../../omnetpp-5.1/samples/inet/src:../../../../../omnetpp-5.1/samples/inet/tutorials:../../../../../omnetpp-5.1/samples/simulte/simula$


